### ISSUE TITLE
Open work for the display app

### ISSUE THREAD

**Issue by mkristian** [buzzn/core#1059]
just to keep track of the list to do for before the display app is ready to go live:

- [ ] use same short-term cache for charts api endpoints as for bubbles/tickers #1053 - important before several apps showing the same group
- [ ] need roda newrelics plugin #1054 - otherwise the inside into our requests is kind of limited
- [ ] need to optimise redis for caching #1057 - not so important for going live but in the long run we need redis to be configured as LRU cache
- [ ] Group::Base.finalize_registers is broken and untested #1056 - not so important for going live but needs to be fixed 
- [x] the response header on charts tells the wrong expires #1058 - important
- [x] reimplement aggregate endpoints with roda #1046 - important for the old display app
- [x] charts response is the same for in/out with mehrgenerationenplatform on staging #1061 - important
