### ISSUE TITLE
Migrate all BK code - part 2

### ISSUE THREAD

**Issue by dottorer** [buzzn/core#1074]
Continued from #913:

- [ ] #935 mass-create registers when starting a new LCP
- [ ] #922 create energy classification (Stromkennzeichnung) for localpool
- [ ] #941 create all needed PDFs
- [ ] #940 CSV export of complete LCP
