### ISSUE TITLE
virtual meter improvements and use it for the group with discovergy broker

### ISSUE THREAD

**Issue by mkristian** [buzzn/core#1086]
background and the current implementation: we can optimise the groups charts and bubbles by configuring a virtual meter at discovergy and use it for our aggregate requests. this is currently done by assembling a request for discovergy with the `group.registers` - one for the consumption and one for the production registers. our discovergy brokers now can handle following cases:

* groups with two discovergy brokers
* virtual registers with two discovergy brokers
* one way meter (consumption or production)
* two way meters, i.e. has two registers

problems with current setup:

* we do not have any idea what registers we really configured at discovergy
  * no control what happens when we add register to virtual meter or group
  * no control what happens when remove register to virtual meter or group
* we can not delete virtual meters at discovergy (though the API documentation from discovergy itself offers an endpoint to do so(
* both groups and virtual registers are not immutable (with the already mentioned consequences)
* all those different cases seems to simple when looked at in isolation, but the implementation uses if-else clauses everywhere which needs tests which goes over all possible permutations (charts - daily, monthly, hourly, yearly, secondly vs one-way-meter-w-input-register, one-way-meter-w-output-register,two-way-meter, virtual-meters-with-all possible-setups(plus vs minus registers, being input vs output) and groups with discovergy
* we iterate over both 'directions' (`in`, `out`) and filter the results. for virtual meters this means 4 requests to discovergy. but if I have only input registers inside a virtual register, then we can reduce this to one reuest ! similar on two-way meter I can get both `energy` and `energyOut` values with a single request to discovergy and then associate the result to the respective registers

improvements (assume we can delete virtual-meters at discovergy):

* on the low level, the database model `Meter::Virtual` which should be immutable once we setup a `Broker::Discovergy`, i.e. our virtual-meter in the DB matches the configured setup on discovergy side
* on the high level, the client resource `Meter::VirtualResource` do the usual update semantice, allowing to add/remove registers but use a delete/create `Meter::Virtual` with broker on the low level. 
* a group which gets optimised for discovergy means it gets two virtual-registers associated, one for consumption and one for production
* the calls to discovergy should be kept to a minimum, i.e.one request per broker

action points:
- [ ] remove brokers on group and associated virtual-register to a group
- [ ] make low-level virtual-meters with broker immutable
- [ ] optimize/minimize requests to discovergy on virtual registers with broker 

NOTE: need to find out whether or not we can delete virtual-meters at discovergy.
