### ISSUE TITLE
factor out the active admin into own application/repository

### ISSUE THREAD

**Issue by mkristian** [buzzn/core#1141]
**Todos**

- [x] set up initial Rails app and configure active admin
  - [x] generate app
  - [x] configure DB
  - [x] add dotenv & config
  - [x] strip down Rails to what's needed (remove actioncable, turbolinks, etc.)
- [x] move model config files from old admin (add minimal stubs for active record models) 
  - [x] make them readonly by default (ApplicationRecord)!!!
- [x] remove activeadmin from old app
- [x] ~~check if select2 works / replace it with another improved select field~~ -- will do this as part of https://github.com/buzzn/buzzn/issues/1162 which is the only resource that will be edited for now.
- [x] ~~set up CI job~~ --> on hold
- [x] discuss open issues (see below)
- [x] (WIP) dockerize app 
- [x] include app in deployment so it becomes available on staging/prod

**To discuss**
- [x] add simple integration test to verify authentication (would require a separate CI build)
- [x] discuss if app should only be served with https
- [x] is select2 required in the buzzn app?
- [x] discuss if duplicated models (stubs only) are Ok. There's no simple, convenient and DRY way to use the models of the core application here, IMHO. --> discuss with Christian / Thursday
- [x] discuss implications of direct access to DB "around" the core app. Business logic there will be circumvented. Readonly? --> readonly for now, discuss case per case

the idea is to have our API server in slim repo and strip rails as much as possible, i.e. just use ActiveRecord for the API

for the active-admin use the db/structure.sql to setup the database and AR uses the DB as defining source of the model classes. active_admin just needs for each DB table one AR model class (basically empty) and its active-admin counterpart. in this sense the active-admin is tiny rails app with inherited db/structure.sql
