### ISSUE TITLE
ActiveAdmin: adapt groups

### ISSUE THREAD

**Issue by phillipoertel** [buzzn/core#1160]
**Todos**

_List_ 
- [x] remove batches
- [x] separate scopes for localpool / tribe
- [x] show number of powertakers
- [x] remove UUID
- [x] link name

_Detail_
- [x] show local pool power taker contracts
	- contract number
	- taker name (contracting parties customer name)
	- link powertaker
- [x] show meters & registers
- [x] show other contracts
  - messtellen vertrag (metering point contract)
  - betreiber
  - powertaker
  - powergiver
- [x] link registers
