### ISSUE TITLE
EPIC: cleanup standard_profile datasource

### ISSUE THREAD

**Issue by ffaerber** [buzzn/core#709]
i merged https://github.com/buzzn/buzzn/pull/669 because of 'it works and i need to deliver' but there are some enhancements in the PR Which I have not done. so this ticket is about implementing the enhancements and tests them.

- [ ] standard profile datasourec does not implement the specification of datasource: #713
- [ ] standard datasource does not handle interval in UTC: #714
- [ ] chart calulation do all have a systematical error: #484
- [ ] #197 is back as the fix from c859f59 was not moved to the new implementation.
- [ ] standard profile datasource uses highly ineffecient date arithmetic: #716
- [ ] and there are a few other little things which would have be 5 minutes work to fix them before merging.
