### ISSUE TITLE
EPIC: new APIs for Admin App

### ISSUE THREAD

**Issue by dottorer** [buzzn/core#731]
In https://github.com/buzzn/profile-app/issues/54 we are defining the front end work to implement buzzn/ux#28. For this we will need several new APIs to provide CRUD on this data in a secure, robust and scalable way. This Epic tracks all the required work.

- [x] #743 Contracts for local group
- [x] #752 get contracting_party data from api
- [x] #848 get group meters from api
- [x] #733 API for bank account of LocalPool
- [x] #906 Endpoint for LCP power takers
