### ISSUE TITLE
Migrate all BK code - part 1

### ISSUE THREAD

**Issue by ChriWiChris** [buzzn/core#913]
All functional code should be migrated from Beekeeper into platform incl. testware for each individual function.
- [x] #902 energy/reading caclulations
- [x] #924 EEG taxation and ÜGZ corrected
- [x] #932 converter constant
- [x] #938 get readings from discovergy and store them
- [x] #961 create new models BillingCycle and Billing
- [x] #968 attributes constants
- [x] #972 bank_account to contracts
- [x] #939 check for LSN contracts at consumption registers
- [x] #991 create pricing model
- [x] #984 billing cycle API and functionality
- [x] #934 create LCP report
- [x] #923 PDF creation and handling
- [x] #412 create A01 as PDF out of the system (proof-of-concept)
