### ISSUE TITLE
Epic: API framework 2.0

### ISSUE THREAD

**Issue by dottorer** [buzzn/core#997]
We need to refactor our current API technology to leverage the following:

- [x] #998 use roda-tree
- [x] #954 use active model serializers with default adapter
- [x] #999 support n-level deep object requests
- [x] #1000 remove all obsolete rails API code
- [x] #1001 connect swagger
- [x] #1039 SwaggerJSON by roda
